name: GMF_Shop_Plugin
version: 1.0.0-pre-alpha
author: GMF MC Dev Team
main: com.gmf.mc.shop.ShopPlugin
api-version: 1.16
commands:
  shop_help:
    description: get shop help info
    usage: /shop_help
  balance:
    description: узнать свое количество козкоинов. Если реплаем, то пользователя в реплае.
    usage: /balance
  pay:
    description: перечислить со своего счёта деньги на счёт пользователя
    usage: /pay [to] [count] [comment]
  rating:
    description: рейтинг
    usage: /rating